#include <bits/stdc++.h>

using namespace std;

int main(){
    int n , k ;
    cin >> n ;
    cin >> k;
    int arr[n];
    int max = INT8_MIN;
    
    
    for( int i =0 ; i< n ; i++){
         cin>> arr[i];
         
        
       if(arr[i]>= max){
           max = arr[i];
           
       }
    }
    
    if(max < k){
        cout<< "0"<<endl;
        
    }
    else{
        cout<<(max-k)<<endl ;
    }
    
}